// Generated by scripts/generate_team_registry.py. Do not edit by hand.
import Foundation

struct NewsSource: Hashable, Identifiable, Sendable {
    let key: String
    let name: String

    var id: String { key }
    var shortName: String { name }
    var fileName: String { key }
}

struct HubTeamColors: Sendable {
    let primary: String
    let secondary: String
    let background: String
    let ink: String
    let border: String
    let positive: String
    let banner: String
    let accentDark: String
    let navigation: String
    let teamTint: String
    let teamLine: String

    init(
        primary: String, secondary: String, background: String, ink: String,
        border: String, positive: String, banner: String, accent_dark: String,
        navigation: String, team_tint: String, team_line: String
    ) {
        self.primary = primary
        self.secondary = secondary
        self.background = background
        self.ink = ink
        self.border = border
        self.positive = positive
        self.banner = banner
        self.accentDark = accent_dark
        self.navigation = navigation
        self.teamTint = team_tint
        self.teamLine = team_line
    }
}

struct HubTeamFeatures: Sendable {
    let nativePicker: Bool
    let home: Bool
    let recentGame: Bool
    let schedule: Bool
    let standings: Bool
    let pitching: Bool
    let leaders: Bool
    let news: Bool
    let xPosts: Bool
    let players: Bool
    let stories: Bool

    init(
        native_picker: Bool, home: Bool, recent_game: Bool, schedule: Bool,
        standings: Bool, pitching: Bool, leaders: Bool, news: Bool,
        x_posts: Bool, players: Bool, stories: Bool
    ) {
        self.nativePicker = native_picker
        self.home = home
        self.recentGame = recent_game
        self.schedule = schedule
        self.standings = standings
        self.pitching = pitching
        self.leaders = leaders
        self.news = news
        self.xPosts = x_posts
        self.players = players
        self.stories = stories
    }
}

struct HubTeamDefinition: Sendable {
    let mlbID: Int
    let fullName: String
    let cityName: String
    let shortName: String
    let abbreviation: String
    let cityAbbreviation: String
    let apiKey: String
    let dataDirectory: String
    let xHandle: String
    let usesLegacyRootData: Bool
    let league: String
    let division: String
    let fangraphsID: Int
    let baseballReferenceID: String
    let colors: HubTeamColors
    let newsSources: [NewsSource]
    let features: HubTeamFeatures
}

enum HubTeam: String, CaseIterable, Identifiable, Sendable {
    case boston = "boston"
    case newYork = "new-york"
    case newYorkMets = "new-york-mets"
    case tampaBay = "tampa-bay"
    case baltimore = "baltimore"
    case toronto = "toronto"
    case chicagoWhiteSox = "chicago-white-sox"
    case cleveland = "cleveland"
    case detroit = "detroit"
    case kansasCity = "kansas-city"
    case minnesota = "minnesota"
    case houston = "houston"
    case losAngelesAngels = "los-angeles-angels"
    case athletics = "athletics"
    case seattle = "seattle"
    case texas = "texas"
    case atlanta = "atlanta"
    case miami = "miami"
    case philadelphia = "philadelphia"
    case washington = "washington"
    case chicagoCubs = "chicago-cubs"
    case cincinnati = "cincinnati"
    case milwaukee = "milwaukee"
    case pittsburgh = "pittsburgh"
    case stLouis = "st-louis"
    case arizona = "arizona"
    case colorado = "colorado"
    case losAngelesDodgers = "los-angeles-dodgers"
    case sanDiego = "san-diego"
    case sanFrancisco = "san-francisco"

    nonisolated private static let registry: [HubTeam: HubTeamDefinition] = [
        .boston: .init(
            mlbID: 111, fullName: "Boston Red Sox",
            cityName: "Boston", shortName: "Red Sox",
            abbreviation: "BOS", cityAbbreviation: "BOS",
            apiKey: "redsox", dataDirectory: "redsox",
            xHandle: "RedSox",
            usesLegacyRootData: true, league: "AL",
            division: "East", fangraphsID: 3,
            baseballReferenceID: "BOS",
            colors: .init(primary: "#BD3039", secondary: "#15324B", background: "#EAF1F6", ink: "#17212B", border: "#D8E1E8", positive: "#287052", banner: "#B8333D", accent_dark: "#8B0C13", navigation: "#133E2D", team_tint: "#211817", team_line: "#D83C45"),
            newsSources: [.init(key: "globe", name: "Globe"), .init(key: "herald", name: "Herald"), .init(key: "athletic", name: "The Athletic"), .init(key: "masslive", name: "MassLive")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: true)
        ),
        .newYork: .init(
            mlbID: 147, fullName: "New York Yankees",
            cityName: "New York", shortName: "Yankees",
            abbreviation: "NYY", cityAbbreviation: "NY",
            apiKey: "yankees", dataDirectory: "yankees",
            xHandle: "Yankees",
            usesLegacyRootData: false, league: "AL",
            division: "East", fangraphsID: 9,
            baseballReferenceID: "NYY",
            colors: .init(primary: "#0C2340", secondary: "#0C2340", background: "#E8EEF4", ink: "#061527", border: "#C6D2DE", positive: "#1B3F65", banner: "#0C2340", accent_dark: "#061527", navigation: "#0C2340", team_tint: "#141F30", team_line: "#E8E4DA"),
            newsSources: [.init(key: "dailynews", name: "Daily News"), .init(key: "nypost", name: "NY Post"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .newYorkMets: .init(
            mlbID: 121, fullName: "New York Mets",
            cityName: "New York", shortName: "Mets",
            abbreviation: "NYM", cityAbbreviation: "NY",
            apiKey: "mets", dataDirectory: "mets",
            xHandle: "Mets",
            usesLegacyRootData: false, league: "NL",
            division: "East", fangraphsID: 25,
            baseballReferenceID: "NYM",
            colors: .init(primary: "#FF5910", secondary: "#002D72", background: "#EAF1FA", ink: "#061A35", border: "#C6D4E6", positive: "#002D72", banner: "#FF5910", accent_dark: "#C33A00", navigation: "#002D72", team_tint: "#211815", team_line: "#F84C00"),
            newsSources: [.init(key: "dailynews", name: "Daily News"), .init(key: "nypost", name: "NY Post"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .tampaBay: .init(
            mlbID: 139, fullName: "Tampa Bay Rays",
            cityName: "Tampa Bay", shortName: "Rays",
            abbreviation: "TB", cityAbbreviation: "TB",
            apiKey: "rays", dataDirectory: "rays",
            xHandle: "RaysBaseball",
            usesLegacyRootData: false, league: "AL",
            division: "East", fangraphsID: 12,
            baseballReferenceID: "TBR",
            colors: .init(primary: "#007AB2", secondary: "#092647", background: "#E7F3FA", ink: "#051B32", border: "#B5D2E1", positive: "#669E29", banner: "#669E29", accent_dark: "#004F80", navigation: "#092647", team_tint: "#141C21", team_line: "#8FBCE6"),
            newsSources: [.init(key: "tampabay", name: "Tampa Bay Times"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .baltimore: .init(
            mlbID: 110, fullName: "Baltimore Orioles",
            cityName: "Baltimore", shortName: "Orioles",
            abbreviation: "BAL", cityAbbreviation: "BAL",
            apiKey: "orioles", dataDirectory: "orioles",
            xHandle: "Orioles",
            usesLegacyRootData: false, league: "AL",
            division: "East", fangraphsID: 2,
            baseballReferenceID: "BAL",
            colors: .init(primary: "#DF4601", secondary: "#27251F", background: "#F8EEE8", ink: "#27251F", border: "#DFCBBF", positive: "#4B6B3C", banner: "#DF4601", accent_dark: "#27251F", navigation: "#27251F", team_tint: "#211816", team_line: "#F64D01"),
            newsSources: [.init(key: "baltimore-sun", name: "Baltimore Sun"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .toronto: .init(
            mlbID: 141, fullName: "Toronto Blue Jays",
            cityName: "Toronto", shortName: "Blue Jays",
            abbreviation: "TOR", cityAbbreviation: "TOR",
            apiKey: "bluejays", dataDirectory: "bluejays",
            xHandle: "BlueJays",
            usesLegacyRootData: false, league: "AL",
            division: "East", fangraphsID: 14,
            baseballReferenceID: "TOR",
            colors: .init(primary: "#134A8E", secondary: "#1D2D5C", background: "#E9F1F8", ink: "#10213B", border: "#C3D4E4", positive: "#2D6A4F", banner: "#134A8E", accent_dark: "#1D2D5C", navigation: "#1D2D5C", team_tint: "#161B22", team_line: "#3A74CF"),
            newsSources: [.init(key: "toronto-star", name: "Toronto Star"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .chicagoWhiteSox: .init(
            mlbID: 145, fullName: "Chicago White Sox",
            cityName: "Chicago", shortName: "White Sox",
            abbreviation: "CWS", cityAbbreviation: "CHI",
            apiKey: "whitesox", dataDirectory: "whitesox",
            xHandle: "whitesox",
            usesLegacyRootData: false, league: "AL",
            division: "Central", fangraphsID: 4,
            baseballReferenceID: "CHW",
            colors: .init(primary: "#27251F", secondary: "#C4CED4", background: "#F0F1F1", ink: "#1B1B1B", border: "#CED3D6", positive: "#435A4B", banner: "#27251F", accent_dark: "#C4CED4", navigation: "#C4CED4", team_tint: "#14293D", team_line: "#C4CED4"),
            newsSources: [.init(key: "chicago-tribune", name: "Chicago Tribune"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .cleveland: .init(
            mlbID: 114, fullName: "Cleveland Guardians",
            cityName: "Cleveland", shortName: "Guardians",
            abbreviation: "CLE", cityAbbreviation: "CLE",
            apiKey: "guardians", dataDirectory: "guardians",
            xHandle: "CleGuardians",
            usesLegacyRootData: false, league: "AL",
            division: "Central", fangraphsID: 5,
            baseballReferenceID: "CLE",
            colors: .init(primary: "#E50022", secondary: "#00385D", background: "#EAF0F4", ink: "#092033", border: "#C4D0D8", positive: "#2C6E49", banner: "#E50022", accent_dark: "#00385D", navigation: "#00385D", team_tint: "#211817", team_line: "#EC0023"),
            newsSources: [.init(key: "cleveland", name: "Cleveland.com"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .detroit: .init(
            mlbID: 116, fullName: "Detroit Tigers",
            cityName: "Detroit", shortName: "Tigers",
            abbreviation: "DET", cityAbbreviation: "DET",
            apiKey: "tigers", dataDirectory: "tigers",
            xHandle: "tigers",
            usesLegacyRootData: false, league: "AL",
            division: "Central", fangraphsID: 6,
            baseballReferenceID: "DET",
            colors: .init(primary: "#0C2340", secondary: "#FA4616", background: "#EDF1F5", ink: "#0C2340", border: "#CAD3DC", positive: "#3D6B57", banner: "#0C2340", accent_dark: "#FA4616", navigation: "#FA4616", team_tint: "#161B22", team_line: "#FA4616"),
            newsSources: [.init(key: "detroit-free-press", name: "Detroit Free Press"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .kansasCity: .init(
            mlbID: 118, fullName: "Kansas City Royals",
            cityName: "Kansas City", shortName: "Royals",
            abbreviation: "KC", cityAbbreviation: "KC",
            apiKey: "royals", dataDirectory: "royals",
            xHandle: "Royals",
            usesLegacyRootData: false, league: "AL",
            division: "Central", fangraphsID: 7,
            baseballReferenceID: "KCR",
            colors: .init(primary: "#004687", secondary: "#BD9B60", background: "#EAF1F7", ink: "#08243E", border: "#C2D2E0", positive: "#4D704C", banner: "#004687", accent_dark: "#BD9B60", navigation: "#BD9B60", team_tint: "#161B22", team_line: "#3D74CF"),
            newsSources: [.init(key: "kansas-city-star", name: "Kansas City Star"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .minnesota: .init(
            mlbID: 142, fullName: "Minnesota Twins",
            cityName: "Minnesota", shortName: "Twins",
            abbreviation: "MIN", cityAbbreviation: "MIN",
            apiKey: "twins", dataDirectory: "twins",
            xHandle: "Twins",
            usesLegacyRootData: false, league: "AL",
            division: "Central", fangraphsID: 8,
            baseballReferenceID: "MIN",
            colors: .init(primary: "#D31145", secondary: "#002B5C", background: "#EDF1F5", ink: "#0B2137", border: "#C8D2DC", positive: "#3E6B54", banner: "#D31145", accent_dark: "#002B5C", navigation: "#002B5C", team_tint: "#211818", team_line: "#E7134C"),
            newsSources: [.init(key: "star-tribune", name: "Star Tribune"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .houston: .init(
            mlbID: 117, fullName: "Houston Astros",
            cityName: "Houston", shortName: "Astros",
            abbreviation: "HOU", cityAbbreviation: "HOU",
            apiKey: "astros", dataDirectory: "astros",
            xHandle: "astros",
            usesLegacyRootData: false, league: "AL",
            division: "West", fangraphsID: 21,
            baseballReferenceID: "HOU",
            colors: .init(primary: "#EB6E1F", secondary: "#002D62", background: "#F7EFEA", ink: "#10253C", border: "#D8C9BF", positive: "#356A50", banner: "#EB6E1F", accent_dark: "#002D62", navigation: "#002D62", team_tint: "#211915", team_line: "#EB6E1F"),
            newsSources: [.init(key: "houston-chronicle", name: "Houston Chronicle"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .losAngelesAngels: .init(
            mlbID: 108, fullName: "Los Angeles Angels",
            cityName: "Los Angeles", shortName: "Angels",
            abbreviation: "LAA", cityAbbreviation: "LA",
            apiKey: "angels", dataDirectory: "angels",
            xHandle: "Angels",
            usesLegacyRootData: false, league: "AL",
            division: "West", fangraphsID: 1,
            baseballReferenceID: "LAA",
            colors: .init(primary: "#BA0021", secondary: "#003263", background: "#F5EBEE", ink: "#132A40", border: "#D9C5CB", positive: "#356A50", banner: "#BA0021", accent_dark: "#003263", navigation: "#003263", team_tint: "#211817", team_line: "#EC002A"),
            newsSources: [.init(key: "orange-county-register", name: "OC Register"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .athletics: .init(
            mlbID: 133, fullName: "Athletics",
            cityName: "Sacramento", shortName: "Athletics",
            abbreviation: "ATH", cityAbbreviation: "SAC",
            apiKey: "athletics", dataDirectory: "athletics",
            xHandle: "Athletics",
            usesLegacyRootData: false, league: "AL",
            division: "West", fangraphsID: 10,
            baseballReferenceID: "ATH",
            colors: .init(primary: "#003831", secondary: "#EFB21E", background: "#EDF3F0", ink: "#12312D", border: "#C6D7D1", positive: "#007A4D", banner: "#003831", accent_dark: "#EFB21E", navigation: "#EFB21E", team_tint: "#131D1B", team_line: "#118754"),
            newsSources: [.init(key: "nbc-sports-bay-area", name: "NBC Sports Bay Area"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .seattle: .init(
            mlbID: 136, fullName: "Seattle Mariners",
            cityName: "Seattle", shortName: "Mariners",
            abbreviation: "SEA", cityAbbreviation: "SEA",
            apiKey: "mariners", dataDirectory: "mariners",
            xHandle: "Mariners",
            usesLegacyRootData: false, league: "AL",
            division: "West", fangraphsID: 11,
            baseballReferenceID: "SEA",
            colors: .init(primary: "#0C2C56", secondary: "#005C5C", background: "#EAF1F3", ink: "#10283A", border: "#C2D2D6", positive: "#147D6C", banner: "#0C2C56", accent_dark: "#005C5C", navigation: "#005C5C", team_tint: "#161B22", team_line: "#009B8E"),
            newsSources: [.init(key: "seattle-times", name: "Seattle Times"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .texas: .init(
            mlbID: 140, fullName: "Texas Rangers",
            cityName: "Texas", shortName: "Rangers",
            abbreviation: "TEX", cityAbbreviation: "TEX",
            apiKey: "rangers", dataDirectory: "rangers",
            xHandle: "Rangers",
            usesLegacyRootData: false, league: "AL",
            division: "West", fangraphsID: 13,
            baseballReferenceID: "TEX",
            colors: .init(primary: "#C0111F", secondary: "#003278", background: "#EEF1F6", ink: "#102644", border: "#C7D1DF", positive: "#3A6B50", banner: "#C0111F", accent_dark: "#003278", navigation: "#003278", team_tint: "#211817", team_line: "#4473D0"),
            newsSources: [.init(key: "dallas-morning-news", name: "Dallas Morning News"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .atlanta: .init(
            mlbID: 144, fullName: "Atlanta Braves",
            cityName: "Atlanta", shortName: "Braves",
            abbreviation: "ATL", cityAbbreviation: "ATL",
            apiKey: "braves", dataDirectory: "braves",
            xHandle: "Braves",
            usesLegacyRootData: false, league: "NL",
            division: "East", fangraphsID: 16,
            baseballReferenceID: "ATL",
            colors: .init(primary: "#CE1141", secondary: "#13274F", background: "#F1EDF1", ink: "#16253D", border: "#D4C8CF", positive: "#3C6A50", banner: "#CE1141", accent_dark: "#13274F", navigation: "#13274F", team_tint: "#211818", team_line: "#E71349"),
            newsSources: [.init(key: "atlanta-journal-constitution", name: "AJC"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .miami: .init(
            mlbID: 146, fullName: "Miami Marlins",
            cityName: "Miami", shortName: "Marlins",
            abbreviation: "MIA", cityAbbreviation: "MIA",
            apiKey: "marlins", dataDirectory: "marlins",
            xHandle: "Marlins",
            usesLegacyRootData: false, league: "NL",
            division: "East", fangraphsID: 20,
            baseballReferenceID: "MIA",
            colors: .init(primary: "#00A3E0", secondary: "#041E42", background: "#E9F4F8", ink: "#10253B", border: "#C2D7DF", positive: "#32705A", banner: "#00A3E0", accent_dark: "#041E42", navigation: "#041E42", team_tint: "#141C21", team_line: "#00A3E0"),
            newsSources: [.init(key: "miami-herald", name: "Miami Herald"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .philadelphia: .init(
            mlbID: 143, fullName: "Philadelphia Phillies",
            cityName: "Philadelphia", shortName: "Phillies",
            abbreviation: "PHI", cityAbbreviation: "PHI",
            apiKey: "phillies", dataDirectory: "phillies",
            xHandle: "Phillies",
            usesLegacyRootData: false, league: "NL",
            division: "East", fangraphsID: 26,
            baseballReferenceID: "PHI",
            colors: .init(primary: "#E81828", secondary: "#002D72", background: "#F4ECEF", ink: "#102744", border: "#D7C7CD", positive: "#39705A", banner: "#E81828", accent_dark: "#002D72", navigation: "#002D72", team_tint: "#211817", team_line: "#E81929"),
            newsSources: [.init(key: "philadelphia-inquirer", name: "Inquirer"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .washington: .init(
            mlbID: 120, fullName: "Washington Nationals",
            cityName: "Washington", shortName: "Nationals",
            abbreviation: "WSH", cityAbbreviation: "WSH",
            apiKey: "nationals", dataDirectory: "nationals",
            xHandle: "Nationals",
            usesLegacyRootData: false, league: "NL",
            division: "East", fangraphsID: 24,
            baseballReferenceID: "WSN",
            colors: .init(primary: "#AB0003", secondary: "#14225A", background: "#F2EBED", ink: "#18233E", border: "#D4C5CA", positive: "#3C6A50", banner: "#AB0003", accent_dark: "#14225A", navigation: "#14225A", team_tint: "#211817", team_line: "#ED0004"),
            newsSources: [.init(key: "washington-post", name: "Washington Post"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .chicagoCubs: .init(
            mlbID: 112, fullName: "Chicago Cubs",
            cityName: "Chicago", shortName: "Cubs",
            abbreviation: "CHC", cityAbbreviation: "CHI",
            apiKey: "cubs", dataDirectory: "cubs",
            xHandle: "Cubs",
            usesLegacyRootData: false, league: "NL",
            division: "Central", fangraphsID: 17,
            baseballReferenceID: "CHC",
            colors: .init(primary: "#CC3433", secondary: "#0E3386", background: "#EDF0F6", ink: "#15294B", border: "#C9D0DF", positive: "#3C6A50", banner: "#CC3433", accent_dark: "#0E3386", navigation: "#0E3386", team_tint: "#211817", team_line: "#D04443"),
            newsSources: [.init(key: "chicago-tribune", name: "Chicago Tribune"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .cincinnati: .init(
            mlbID: 113, fullName: "Cincinnati Reds",
            cityName: "Cincinnati", shortName: "Reds",
            abbreviation: "CIN", cityAbbreviation: "CIN",
            apiKey: "reds", dataDirectory: "reds",
            xHandle: "Reds",
            usesLegacyRootData: false, league: "NL",
            division: "Central", fangraphsID: 18,
            baseballReferenceID: "CIN",
            colors: .init(primary: "#C6011F", secondary: "#000000", background: "#F4EBED", ink: "#221B1C", border: "#D8C7CB", positive: "#3B6B50", banner: "#C6011F", accent_dark: "#000000", navigation: "#000000", team_tint: "#211817", team_line: "#EC0125"),
            newsSources: [.init(key: "cincinnati-enquirer", name: "Enquirer"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .milwaukee: .init(
            mlbID: 158, fullName: "Milwaukee Brewers",
            cityName: "Milwaukee", shortName: "Brewers",
            abbreviation: "MIL", cityAbbreviation: "MIL",
            apiKey: "brewers", dataDirectory: "brewers",
            xHandle: "Brewers",
            usesLegacyRootData: false, league: "NL",
            division: "Central", fangraphsID: 23,
            baseballReferenceID: "MIL",
            colors: .init(primary: "#FFC52F", secondary: "#12284B", background: "#F8F4E8", ink: "#17263D", border: "#DDD4BD", positive: "#47704D", banner: "#FFC52F", accent_dark: "#12284B", navigation: "#12284B", team_tint: "#1E1A13", team_line: "#8FA8C4"),
            newsSources: [.init(key: "milwaukee-journal-sentinel", name: "Journal Sentinel"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .pittsburgh: .init(
            mlbID: 134, fullName: "Pittsburgh Pirates",
            cityName: "Pittsburgh", shortName: "Pirates",
            abbreviation: "PIT", cityAbbreviation: "PIT",
            apiKey: "pirates", dataDirectory: "pirates",
            xHandle: "Pirates",
            usesLegacyRootData: false, league: "NL",
            division: "Central", fangraphsID: 27,
            baseballReferenceID: "PIT",
            colors: .init(primary: "#FDB827", secondary: "#27251F", background: "#F8F4E8", ink: "#29261F", border: "#DDD4BE", positive: "#48704E", banner: "#FDB827", accent_dark: "#27251F", navigation: "#27251F", team_tint: "#1E1A13", team_line: "#B7B2A8"),
            newsSources: [.init(key: "pittsburgh-post-gazette", name: "Post-Gazette"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .stLouis: .init(
            mlbID: 138, fullName: "St. Louis Cardinals",
            cityName: "St. Louis", shortName: "Cardinals",
            abbreviation: "STL", cityAbbreviation: "STL",
            apiKey: "cardinals", dataDirectory: "cardinals",
            xHandle: "Cardinals",
            usesLegacyRootData: false, league: "NL",
            division: "Central", fangraphsID: 28,
            baseballReferenceID: "STL",
            colors: .init(primary: "#C41E3A", secondary: "#0C2340", background: "#F3ECEE", ink: "#17263B", border: "#D7C7CB", positive: "#3B6B50", banner: "#C41E3A", accent_dark: "#0C2340", navigation: "#0C2340", team_tint: "#211818", team_line: "#DF2D4B"),
            newsSources: [.init(key: "st-louis-post-dispatch", name: "Post-Dispatch"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .arizona: .init(
            mlbID: 109, fullName: "Arizona Diamondbacks",
            cityName: "Arizona", shortName: "Diamondbacks",
            abbreviation: "ARI", cityAbbreviation: "ARI",
            apiKey: "diamondbacks", dataDirectory: "diamondbacks",
            xHandle: "Dbacks",
            usesLegacyRootData: false, league: "NL",
            division: "West", fangraphsID: 15,
            baseballReferenceID: "ARI",
            colors: .init(primary: "#A71930", secondary: "#000000", background: "#F2EBED", ink: "#251C1E", border: "#D5C6CA", positive: "#3D6C51", banner: "#A71930", accent_dark: "#000000", navigation: "#000000", team_tint: "#211818", team_line: "#30CED8"),
            newsSources: [.init(key: "arizona-republic", name: "Arizona Republic"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .colorado: .init(
            mlbID: 115, fullName: "Colorado Rockies",
            cityName: "Colorado", shortName: "Rockies",
            abbreviation: "COL", cityAbbreviation: "COL",
            apiKey: "rockies", dataDirectory: "rockies",
            xHandle: "Rockies",
            usesLegacyRootData: false, league: "NL",
            division: "West", fangraphsID: 19,
            baseballReferenceID: "COL",
            colors: .init(primary: "#33006F", secondary: "#C4CED4", background: "#F0EDF4", ink: "#271D35", border: "#D1C9D9", positive: "#3E6C51", banner: "#33006F", accent_dark: "#C4CED4", navigation: "#C4CED4", team_tint: "#1B1921", team_line: "#8B6DB8"),
            newsSources: [.init(key: "denver-post", name: "Denver Post"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .losAngelesDodgers: .init(
            mlbID: 119, fullName: "Los Angeles Dodgers",
            cityName: "Los Angeles", shortName: "Dodgers",
            abbreviation: "LAD", cityAbbreviation: "LA",
            apiKey: "dodgers", dataDirectory: "dodgers",
            xHandle: "Dodgers",
            usesLegacyRootData: false, league: "NL",
            division: "West", fangraphsID: 22,
            baseballReferenceID: "LAD",
            colors: .init(primary: "#005A9C", secondary: "#EF3E42", background: "#EAF2F8", ink: "#102940", border: "#C3D4E1", positive: "#39705A", banner: "#005A9C", accent_dark: "#EF3E42", navigation: "#EF3E42", team_tint: "#151B21", team_line: "#3773D7"),
            newsSources: [.init(key: "los-angeles-times", name: "LA Times"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .sanDiego: .init(
            mlbID: 135, fullName: "San Diego Padres",
            cityName: "San Diego", shortName: "Padres",
            abbreviation: "SD", cityAbbreviation: "SD",
            apiKey: "padres", dataDirectory: "padres",
            xHandle: "Padres",
            usesLegacyRootData: false, league: "NL",
            division: "West", fangraphsID: 29,
            baseballReferenceID: "SDP",
            colors: .init(primary: "#2F241D", secondary: "#FFC425", background: "#F5F0E8", ink: "#2B251F", border: "#D8CEBE", positive: "#4A704E", banner: "#2F241D", accent_dark: "#FFC425", navigation: "#FFC425", team_tint: "#201914", team_line: "#A47552"),
            newsSources: [.init(key: "san-diego-union-tribune", name: "Union-Tribune"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        ),
        .sanFrancisco: .init(
            mlbID: 137, fullName: "San Francisco Giants",
            cityName: "San Francisco", shortName: "Giants",
            abbreviation: "SF", cityAbbreviation: "SF",
            apiKey: "giants", dataDirectory: "giants",
            xHandle: "SFGiants",
            usesLegacyRootData: false, league: "NL",
            division: "West", fangraphsID: 30,
            baseballReferenceID: "SFG",
            colors: .init(primary: "#FD5A1E", secondary: "#27251F", background: "#F7EEE9", ink: "#2A231F", border: "#DCCABE", positive: "#47704E", banner: "#FD5A1E", accent_dark: "#27251F", navigation: "#27251F", team_tint: "#211816", team_line: "#FC4502"),
            newsSources: [.init(key: "nbc-sports-bay-area", name: "NBC Sports Bay Area"), .init(key: "athletic", name: "The Athletic")],
            features: .init(native_picker: true, home: true, recent_game: true, schedule: true, standings: true, pitching: true, leaders: true, news: true, x_posts: true, players: true, stories: false)
        )
    ]

    nonisolated var id: String { rawValue }
    nonisolated var definition: HubTeamDefinition { Self.registry[self]! }
    nonisolated var mlbID: Int { definition.mlbID }
    nonisolated var fullName: String { definition.fullName }
    nonisolated var cityName: String { definition.cityName }
    nonisolated var cityAbbreviation: String { definition.cityAbbreviation }
    nonisolated var shortName: String { definition.shortName }
    nonisolated var abbreviation: String { definition.abbreviation }
    nonisolated var pickerTitle: String { definition.fullName }
    nonisolated var apiKey: String { definition.apiKey }
    nonisolated var dataDirectory: String { definition.dataDirectory }
    nonisolated var xHandle: String { definition.xHandle }
    nonisolated var dataPathComponent: String? {
        definition.usesLegacyRootData ? nil : definition.dataDirectory
    }
    nonisolated var colors: HubTeamColors { definition.colors }
    nonisolated var newsSources: [NewsSource] { definition.newsSources }
    nonisolated var features: HubTeamFeatures { definition.features }
    nonisolated var supportsHome: Bool { features.home }
    nonisolated var supportsPlayers: Bool { features.players }
    nonisolated var hasPublishedStories: Bool { features.stories }

    nonisolated static var availableTeams: [HubTeam] {
        allCases
            .filter { $0.features.nativePicker }
            .sorted { $0.fullName.localizedCaseInsensitiveCompare($1.fullName) == .orderedAscending }
    }
}

enum HubPreferences {
    static let selectedTeamKey = "hubSelectedTeam"
    static let completedTeamOnboardingKey = "hubCompletedTeamOnboarding"
}
