#!/usr/bin/env python3
"""Generate native and Netlify registry views from config/mlb-teams.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "config" / "mlb-teams.json"
SWIFT_OUTPUT = ROOT / "ios" / "Hub Ball" / "Hub Ball" / "HubTeam.swift"
JAVASCRIPT_OUTPUT = ROOT / "netlify" / "functions" / "team-registry.mjs"


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def swift_bool(value: bool) -> str:
    return "true" if value else "false"


def swift_source(source: dict[str, str]) -> str:
    return (
        ".init(key: "
        f"{quoted(source['key'])}, name: {quoted(source['name'])}, "
        f"url: {quoted(source['url'])})"
    )


def swift_definition(team: dict[str, Any]) -> str:
    colors = team["colors"]
    features = team["features"]
    sources = ", ".join(swift_source(source) for source in team["news_sources"])
    feature_values = ", ".join(
        f"{key}: {swift_bool(features[key])}"
        for key in (
            "native_picker", "home", "recent_game", "schedule", "standings",
            "pitching", "leaders", "news", "x_posts", "players", "stories",
        )
    )
    color_values = ", ".join(
        f"{key}: {quoted(colors.get(key, fallback))}"
        for key, fallback in (
            ("primary", colors["primary"]),
            ("secondary", colors["secondary"]),
            ("background", colors["background"]),
            ("ink", colors["ink"]),
            ("border", colors["border"]),
            ("positive", colors["positive"]),
            ("banner", colors["primary"]),
            ("accent_dark", colors["secondary"]),
            ("navigation", colors["secondary"]),
        )
    )
    return f"""        .{team['swift_case']}: .init(
            mlbID: {team['mlb_id']}, fullName: {quoted(team['full_name'])},
            cityName: {quoted(team['city_name'])}, shortName: {quoted(team['short_name'])},
            abbreviation: {quoted(team['abbreviation'])}, cityAbbreviation: {quoted(team['city_abbreviation'])},
            apiKey: {quoted(team['api_key'])}, dataDirectory: {quoted(team['data_directory'])},
            usesLegacyRootData: {swift_bool(team['legacy_root_data'])}, league: {quoted(team['league'])},
            division: {quoted(team['division'])}, fangraphsID: {team['fangraphs_id']},
            baseballReferenceID: {quoted(team['baseball_reference_id'])},
            colors: .init({color_values}),
            newsSources: [{sources}],
            features: .init({feature_values})
        )"""


def render_swift(teams: list[dict[str, Any]]) -> str:
    cases = "\n".join(
        f"    case {team['swift_case']} = {quoted(team['id'])}" for team in teams
    )
    definitions = ",\n".join(swift_definition(team) for team in teams)
    return f"""// Generated by scripts/generate_team_registry.py. Do not edit by hand.
import Foundation

struct NewsSource: Hashable, Identifiable, Sendable {{
    let key: String
    let name: String
    let url: String

    var id: String {{ key }}
    var shortName: String {{ name }}
    var fileName: String {{ key }}
}}

struct HubTeamColors: Sendable {{
    let primary: String
    let secondary: String
    let background: String
    let ink: String
    let border: String
    let positive: String
    let banner: String
    let accentDark: String
    let navigation: String

    init(
        primary: String, secondary: String, background: String, ink: String,
        border: String, positive: String, banner: String, accent_dark: String,
        navigation: String
    ) {{
        self.primary = primary
        self.secondary = secondary
        self.background = background
        self.ink = ink
        self.border = border
        self.positive = positive
        self.banner = banner
        self.accentDark = accent_dark
        self.navigation = navigation
    }}
}}

struct HubTeamFeatures: Sendable {{
    let nativePicker: Bool
    let home: Bool
    let recentGame: Bool
    let schedule: Bool
    let standings: Bool
    let pitching: Bool
    let leaders: Bool
    let news: Bool
    let xPosts: Bool
    let players: Bool
    let stories: Bool

    init(
        native_picker: Bool, home: Bool, recent_game: Bool, schedule: Bool,
        standings: Bool, pitching: Bool, leaders: Bool, news: Bool,
        x_posts: Bool, players: Bool, stories: Bool
    ) {{
        self.nativePicker = native_picker
        self.home = home
        self.recentGame = recent_game
        self.schedule = schedule
        self.standings = standings
        self.pitching = pitching
        self.leaders = leaders
        self.news = news
        self.xPosts = x_posts
        self.players = players
        self.stories = stories
    }}
}}

struct HubTeamDefinition: Sendable {{
    let mlbID: Int
    let fullName: String
    let cityName: String
    let shortName: String
    let abbreviation: String
    let cityAbbreviation: String
    let apiKey: String
    let dataDirectory: String
    let usesLegacyRootData: Bool
    let league: String
    let division: String
    let fangraphsID: Int
    let baseballReferenceID: String
    let colors: HubTeamColors
    let newsSources: [NewsSource]
    let features: HubTeamFeatures
}}

enum HubTeam: String, CaseIterable, Identifiable, Sendable {{
{cases}

    nonisolated private static let registry: [HubTeam: HubTeamDefinition] = [
{definitions}
    ]

    nonisolated var id: String {{ rawValue }}
    nonisolated var definition: HubTeamDefinition {{ Self.registry[self]! }}
    nonisolated var mlbID: Int {{ definition.mlbID }}
    nonisolated var fullName: String {{ definition.fullName }}
    nonisolated var cityName: String {{ definition.cityName }}
    nonisolated var cityAbbreviation: String {{ definition.cityAbbreviation }}
    nonisolated var shortName: String {{ definition.shortName }}
    nonisolated var abbreviation: String {{ definition.abbreviation }}
    nonisolated var pickerTitle: String {{ definition.fullName }}
    nonisolated var apiKey: String {{ definition.apiKey }}
    nonisolated var dataDirectory: String {{ definition.dataDirectory }}
    nonisolated var dataPathComponent: String? {{
        definition.usesLegacyRootData ? nil : definition.dataDirectory
    }}
    nonisolated var colors: HubTeamColors {{ definition.colors }}
    nonisolated var newsSources: [NewsSource] {{ definition.newsSources }}
    nonisolated var features: HubTeamFeatures {{ definition.features }}
    nonisolated var supportsHome: Bool {{ features.home }}
    nonisolated var supportsPlayers: Bool {{ features.players }}
    nonisolated var hasPublishedStories: Bool {{ features.stories }}

    nonisolated static var availableTeams: [HubTeam] {{
        allCases.filter {{ $0.features.nativePicker }}
    }}
}}

enum HubPreferences {{
    static let selectedTeamKey = "hubSelectedTeam"
    static let completedTeamOnboardingKey = "hubCompletedTeamOnboarding"
}}
"""


def render_javascript(document: dict[str, Any]) -> str:
    body = json.dumps(document["teams"], indent=2, ensure_ascii=False)
    return f"""// Generated by scripts/generate_team_registry.py. Do not edit by hand.
export const MLB_TEAMS = Object.freeze({body});
export const TEAM_BY_API_KEY = new Map(MLB_TEAMS.map(team => [team.api_key, team]));
export const TEAM_BY_ID = new Map(MLB_TEAMS.map(team => [team.id, team]));
export const TEAM_BY_MLB_ID = new Map(MLB_TEAMS.map(team => [team.mlb_id, team]));
"""


def write_or_check(path: Path, content: str, check: bool) -> bool:
    if check:
        return path.exists() and path.read_text() == content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    document = json.loads(SOURCE.read_text())
    outputs = {
        SWIFT_OUTPUT: render_swift(document["teams"]),
        JAVASCRIPT_OUTPUT: render_javascript(document),
    }
    stale = [path for path, content in outputs.items() if not write_or_check(path, content, args.check)]
    if stale:
        names = ", ".join(str(path.relative_to(ROOT)) for path in stale)
        raise SystemExit(f"Generated team registry files are stale: {names}")
    if not args.check:
        print("Generated " + ", ".join(str(path.relative_to(ROOT)) for path in outputs))


if __name__ == "__main__":
    main()
