#!/usr/bin/env python3
"""Generate the workflow schedule table used by the Netlify workflow timer.

GitHub's own `schedule:` triggers are best-effort and are often delayed or
skipped, so netlify/functions/workflow-timer.mjs starts each refresh workflow
through the GitHub API when its cron is due. The cron lines in
.github/workflows/*.yml stay the single source of truth; this script copies
them into netlify/functions/workflow-schedules.mjs. Run it after changing a
workflow's schedule (`--check` fails if the table is stale).
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS = ROOT / ".github" / "workflows"
OUTPUT = ROOT / "netlify" / "functions" / "workflow-schedules.mjs"
CRON = re.compile(r"""^\s*-\s*cron:\s*['"]([^'"]+)['"]""", re.MULTILINE)


def dispatch_inputs(text: str) -> list[str]:
    """Names of `workflow_dispatch` inputs (indented one level under `inputs:`)."""
    match = re.search(r"^  workflow_dispatch:\s*\n((?:    .*\n|\s*\n)*)", text, re.MULTILINE)
    if not match:
        return []
    block = match.group(1)
    inputs = re.search(r"^    inputs:\s*\n((?:      .*\n|\s*\n)*)", block, re.MULTILINE)
    if not inputs:
        return []
    return re.findall(r"^      ([A-Za-z_][\w-]*):", inputs.group(1), re.MULTILINE)


def schedules() -> list[dict]:
    rows = []
    for path in sorted(WORKFLOWS.glob("*.yml")):
        text = path.read_text()
        crons = CRON.findall(text)
        if not crons:
            continue
        if not re.search(r"^  workflow_dispatch:", text, re.MULTILINE):
            raise SystemExit(f"{path.name} has a schedule but cannot be dispatched")
        row = {"workflow": path.name, "crons": crons}
        # Workflows that act differently on a scheduled run declare a `scheduled`
        # input; the timer sets it so its runs behave like GitHub's cron runs.
        if "scheduled" in dispatch_inputs(text):
            row["inputs"] = {"scheduled": "true"}
        rows.append(row)
    return rows


def render() -> str:
    body = json.dumps(schedules(), indent=2)
    return (
        "// Generated by scripts/generate_workflow_schedules.py from the cron lines in\n"
        "// .github/workflows/*.yml. Do not edit by hand.\n"
        f"export const WORKFLOW_SCHEDULES = Object.freeze({body});\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            raise SystemExit(
                f"{OUTPUT.relative_to(ROOT)} is stale; run scripts/generate_workflow_schedules.py"
            )
        print("Workflow schedule table is current.")
        return
    OUTPUT.write_text(content)
    print(f"Generated {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
